### ISSUE TITLE
Hi bro

### ISSUE THREAD

**Issue by huichen5796** [QiyangZ/I2DL_TUM#1]
@QiyangZ  hi I am a Ausländer and can not verstehen das Word --> **yasuobao**

was ist das?
see hier: 
![image](https://user-images.githubusercontent.com/79353997/187899797-c844e18b-b34f-4f82-b802-36962d52fe1a.png)

**Comment by QiyangZ** [comment]
Das ist Chinesisch, and du can ignoren.

**Comment by huichen5796** [comment]
爷关更
